name = "availability"
main = "src/index.js"
compatibility_date = "2026-08-01"
workers_dev = true
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "hollybush-club"
database_id = "a2ad2fb9-6182-4ea5-a188-cbc228d74808"

# Store the squad PIN with: npx wrangler secret put SQUAD_PIN
